# Generated by Django 3.2.8 on 2021-10-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0002_auto_20211029_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='location',
        ),
    ]
