# Generated by Django 3.2.8 on 2021-12-03 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allocate', '0005_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='jobTitle',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocate.allocation'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
