# Generated by Django 3.2.8 on 2021-12-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0006_auto_20211203_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocate.course'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocate.staff'),
        ),
    ]
